baseurl = "https://xenodochial-engelbart-5db29b.netlify.com/"
title = "Home"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Kenny Day"
googleAnalytics = "XXX"
disqusShortname = "XXX"

[Privacy]

[Privacy.disqus]
    disable = true

[Privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = false

[Author]
    name = "Kenny Day"
    profile = "https://google.com/+XXX"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "Kenny Day"
    description = "Fullstack Software Engineer"
    github = "https://github.com/dimxasnewfrozen"
    linkedin = "https://www.linkedin.com/in/kenny-day-89069525"
    twitter = "https://twitter.com/dimxasnewfrozen"
    shareTwitter = true
    shareFacebook = true
    shareGooglePlus = true
    shareLinkedIn = true
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""
    exponeaJsUrl = ""
    exponeaTarget = ""
    exponeaToken = ""
    exponeaTrackVisits = false

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/project/"
    weight = 2

[[menu.main]]
    name = "Contact"
    url = "/page/contact"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/page/about"
    weight = 4